### ISSUE TITLE
Resnet 50 v1 or v2?

### ISSUE THREAD

**Issue by aeitel** [pmorerio/admd#11]
Hello Pietro,
the checkpoint in your repo links to Resnet 50 v2 http://download.tensorflow.org/models/resnet_v2_50_2017_04_14.tar.gz
In your paper and in your code you mention using the Resnet 50 v1.
I am able to run your code using the model v1 ( resnet_v1_50_2016_08_28.tar.gz), which I downloaded directly from the tensorflow webpage.
Unfortunately I did not manage to run your code with the resnet_v2_50_2017_04_14.tar.gz model.
Could you maybe clarify which one is the correct model?

**Comment by pmorerio** [comment]
You are right, my mistake. Thanks for the feedback.
I fixed it.

**Comment by pmorerio** [comment]
@aeitel pull request #12 should link to the correct checkpoint.
