### ISSUE TITLE
How to run the code on NTU for Action Recignition

### ISSUE THREAD

**Issue by ENDLICHERE** [pmorerio/admd#13]
hi,

I would like to reimplement the results of your paper on NTU dataset, but I don't know how to orginize the dataset form.
Could you please share the NTU file form :)
Thanks.

**Comment by pmorerio** [comment]
@ncgarcia could you help on this?

**Comment by ENDLICHERE** [comment]
I find the answer in your previous project:     https://github.com/ncgarcia/modality-distillation/issues/2
