### ISSUE TITLE
Theoretical question about your TPAMI paper

### ISSUE THREAD

**Issue by vandana-rajan** [pmorerio/admd#14]
Hi,

I have a doubt about the discriminator design of ADMD method. 

In ADMD discriminator you have used label 0 for real and label 1 for generated/fake samples. Usually, I have seen people using label 1 for real and label 0 for fake samples. Why is it the other way around in ADMD? 

Also, for the extended label vector, zeros(C) is used for RGB inputs. Why zeros(C) for RGB and the true y label for depth inputs? What does the zeros(C) signify?

Thanks,

**Comment by pmorerio** [comment]
Hi,
suppose you have a classification problem with 10 classes (0-9).
You define a 10+1 **one-hot label vector** for you problem ($\hat{y}$, eq. 1). The first chunk of the vector is overall assigned to real samples (i.e. depth feature vectors in this case), while the extra class at the end is assigned to fake samples only (i.e. features hallucinated from RGB). 
So suppose you have a depth sample belonging to class 5: its extended label vector will be [0,0,0,0,0,1,0,0,0,0,**0**].
For any RGB sample you have instead [0,0,0,0,0,0,0,0,0,0,**1**].
The loss is not binary anymore for the Discriminator. In fact this is a multiclass problem, where D is trying to discriminate not only real vs fake, but also the correct class for real samples.
Here comes your doubt about 0/1, which is not a binary label here, but instead the value assigned to the last entry of the one-hot vector, i.e. the one corresponding to the class 'fake': you want that entry to be 1 for fake classes only.

On the other hand the Generator (the Hallucination network here) is trained to maximize the loss of eq. 2 with the 'label flipping' trick. This means that for real (i.e. depth) examples it will try to drive D towards predicting [0,0,0,0,0,0,0,0,0,0,**1**], (i.e. towards predicting 'fake'), while it will try to generate feature vectors belonging to the correct class for RGB. This is how the Hallucination network H retains some discriminative power for the orginal classification task.

Hope this clarifies you doubt.
Best,
P.

**Comment by vandana-rajan** [comment]
Thanks a lot for the detailed explanation.

Just to be sure that I understood it correctly, I am repeating here what I understood.

In step 2 training where the real depth network is frozen, the discriminator is trained by using 10 class labels (1 hot encoding where last entry is always zero) for depth images and a 1 class label (1 hot encoding where always the last entry is 1 with rest all zeros) for the RGB stream (H). When one forward and backward pass of discriminator is done, discriminator is frozen and then the generator (H) is trained with labels flipped, such that H will eventually produce the 10 class discriminative features.

Please correct me if I am wrong.

Thanks,

**Comment by pmorerio** [comment]
Yes, your understanding is correct!
However in practice in the code I use two separate optimizers, one for H and one for D instead of alternately 'freezing' the two modules. It should be equivalent.
Best,
P.
