### ISSUE TITLE
Northwestern-UCLA dataset

### ISSUE THREAD

**Issue by punknownq** [pmorerio/admd#16]
Hi, can you provide the download link of Northwestern-UCLA dataset?

**Comment by pmorerio** [comment]
https://wangjiangb.github.io/my_data.html

**Comment by punknownq** [comment]
Thank you for your reply. I have downloaded the dataset and I noted that there are three kinds of depth data in a folder. Could you tell me which one do you use?

**Comment by punknownq** [comment]
There are named "*_depth.png", "_depth_vis.jpg" and "*_maprgbd.png".
